permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: blog
      comments: true
