permalink: pretty
gems:
  - jekyll-emoji
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - s3_website.yml
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: blog
