name: Deploy to S3
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
    - name: Set up Ruby environment
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.6
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y python3-pip
        gem install bundler -v '1.17.3'
        bundle install
        pip3 install awscli s3cmd
    - name: Deploy to S3
      env:
        S3_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        S3_SECRET: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        CLOUD_FRONT_ID: ${{ secrets.CLOUD_FRONT_ID }}
      run: bundle exec rake deploy
